theme: jekyll-theme-midnight
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=MjM2aHQ0cjFxcjY0YzdpNXA5NHJ1MG9sZmYgb2xlc25pa29uQG0&amp;tmsrc=olesnikon%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_ru.gif"></a>
